name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: latest

    - name: install
      run: make install

    - name: Run linter
      run: make lint

    - name: Run test & publish code coverage
      uses: paambaati/codeclimate-action@v5
    
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test-coverage
        coverageLocations: build/logs/clover.xml:clover
        debug: true

    